// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6owvQc6wuRBdV5jlzlZXJ4lSHjfEJJ5Y',
    appId: '1:581719948205:web:469def650366d8f4aebf24',
    messagingSenderId: '581719948205',
    projectId: 'aldevpersonal',
    authDomain: 'aldevpersonal.firebaseapp.com',
    storageBucket: 'aldevpersonal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBJ7-A5h-w-7k8vTzu-fdnN7g-QADP7t4',
    appId: '1:581719948205:android:7c7185fc596c4606aebf24',
    messagingSenderId: '581719948205',
    projectId: 'aldevpersonal',
    storageBucket: 'aldevpersonal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Ltr5DZ9PM94UOhr7RtaZ_Ubc72vdhjA',
    appId: '1:581719948205:ios:29a66ed3492c4c64aebf24',
    messagingSenderId: '581719948205',
    projectId: 'aldevpersonal',
    storageBucket: 'aldevpersonal.firebasestorage.app',
    iosClientId: '581719948205-aaaddr0167ta0jj1rf7a8ks2fuikab9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.aldevpersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Ltr5DZ9PM94UOhr7RtaZ_Ubc72vdhjA',
    appId: '1:581719948205:ios:29a66ed3492c4c64aebf24',
    messagingSenderId: '581719948205',
    projectId: 'aldevpersonal',
    storageBucket: 'aldevpersonal.firebasestorage.app',
    iosClientId: '581719948205-aaaddr0167ta0jj1rf7a8ks2fuikab9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.aldevpersonal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6owvQc6wuRBdV5jlzlZXJ4lSHjfEJJ5Y',
    appId: '1:581719948205:web:36bbab5370e1bda2aebf24',
    messagingSenderId: '581719948205',
    projectId: 'aldevpersonal',
    authDomain: 'aldevpersonal.firebaseapp.com',
    storageBucket: 'aldevpersonal.firebasestorage.app',
  );

}